import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Frequently Asked Questions | Green Living Calculator',
    description: 'Find answers to common questions about green living, sustainability, and reducing your carbon footprint.',
    keywords: 'green living FAQ, sustainability questions, eco-friendly living, carbon footprint reduction',
}

const faqs = [
    {
        question: "What is a carbon footprint?",
        answer: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions."
    },
    {
        question: "How can I reduce my carbon footprint?",
        answer: "You can reduce your carbon footprint by using energy-efficient appliances, reducing meat consumption, using public transportation or carpooling, and minimizing waste."
    },
    {
        question: "What is sustainable living?",
        answer: "Sustainable living is a lifestyle that attempts to reduce an individual's or society's use of the Earth's natural resources and personal resources."
    },
    {
        question: "How does diet affect my carbon footprint?",
        answer: "Diet has a significant impact on your carbon footprint. Generally, plant-based diets have a lower carbon footprint than meat-heavy diets due to the resources required for animal agriculture."
    },
    {
        question: "What are some easy ways to be more eco-friendly?",
        answer: "Some easy ways to be more eco-friendly include using reusable bags and water bottles, turning off lights when not in use, recycling, and choosing products with minimal packaging."
    }
]

export default function FAQ() {
    return (
        <div className="min-h-screen p-8">
            <h1 className="text-4xl font-bold text-center mb-8 text-green-800">Frequently Asked Questions</h1>
            <div className="max-w-3xl mx-auto dark:text-black">
                {faqs.map((faq, index) => (
                    <div key={index} className="mb-6 bg-white p-6 rounded-lg shadow-md">
                        <h2 className="text-xl font-semibold text-green-700 mb-2">{faq.question}</h2>
                        <p>{faq.answer}</p>
                    </div>
                ))}
            </div>
            <div className="mt-8 text-center">
                <Link href="/" className="bg-green-600 text-white py-2 px-4 rounded-md hover:bg-green-700 transition-colors">
                    Back to Calculator
                </Link>
            </div>
            {/* Google Ads */}
            {/* <div className="mt-8 text-center">
                <p className="text-sm text-gray-500">Advertisement</p>
                <div className="bg-gray-200 p-4 rounded-md">
                    Replace this with actual Google Ads code
                    <p className="text-gray-700">Google Ads Placeholder</p>
                </div>
            </div> */}
        </div>
    )
}